// export class ProjectDto {
//     public Id: number;
//     public name: string;
// }


// Generated by https://quicktype.io

export interface ProjectDto {
    projects: Project[];
}

export interface Project {
    id:   number;
    name: string;
}
